---
title: "Bayesian multi-proxy reconstruction of latitudinal temperature gradients for the Early Eocene"

author:
  - Kilian Eichenseer^[Department of Earth Sciences, Durham University, South Road, DH1 3LE, Durham, United Kingdom] and Lewis A. Jones^[Centro de Investigación Mariña, Grupo de Ecoloxía Animal, Universidade de Vigo, 36310 Vigo, Spain]
output:
  word_document:
    reference_docx: "template.docx"


bibliography: references.bib
csl: palaeontology.csl



---


<!-- discarded titles:
Bayesian multi-proxy reconstruction of the early Eocene latitudinal temperature gradient
Combining geochemical and ecological proxies...
Modelling latitudinal temperature gradients from geological proxies: An early Eocene example
"Improving palaeoclimatic reconstructions with ecological data: How hot was the early Eocene?"
"Integrating ecological and geochemical proxies for palaeoclimatic reconstruction: An early Eocene example"
"The Early Eocene Climate Optimum reconstructed with Bayesian multi-proxy integration"
"An Early Eocene temperature gradient modelled with geological and ecological proxies"
-->

Abstract
===============================================================================
Geochemical data such as oxygen isotopes (d18O), tetraether indices (TEX86) and magnesium calcium ratios (Mg/Ca) are routinely used to reconstruct ocean temperatures in deep time. However, limited spatial coverage and disagreements between geochemical proxies compromise the accuracy of these reconstructions. Geological data such as coral reefs, mangroves, and evaporites have the potential to supplement geochemical data by improving spatial coverage and constraining temperature estimates. Historically, these data have been used to qualitatively inform upon palaeoclimatic conditions at broad spatial scales, yet no transfer functions exist to convert geological data into temperature estimates. Quantitative temperature reconstructions have therefore not made use of these data. Here, we present a Bayesian hierarchical model to integrate geological data–with established temperature proxies–into a unified quantitative framework. We apply this approach to the early Eocene climatic optimum (EECO), the interval with the warmest sustained temperatures of the Cenozoic. Assuming the conservation of thermal tolerances of modern coral reefs and mangrove taxa, we establish broad sea surface temperature ranges for EECO coral reef and mangrove sites. We integrate these temperature estimates with the EECO geochemical shallow marine proxy record to model the latitudinal temperature gradient and its uncertainty. Our results confirm the presence of a flattened latitudinal temperature gradient and unusually high polar temperatures during the EECO. We show that the inclusion of ecological data can substantially reduce the uncertainty on temperature estimates in climate zones lacking geochemical data.

# Introduction
The geological record holds evidence for episodes in Earth history with fundamentally different climates than our current [@Scotese2021]. Some episodes, for example the early Eocene, are thought to have been significantly warmer than the modern [@Pross2012], potentially representing an analogue for extreme climate warming scenarios [@Burke2018]. Reconstructions of palaeoclimate commonly use geochemical proxy data, palaeobiological or lithological climate indicators, or earth system modelling. 

Geochemical proxies such as oxygen isotopes (d18O), tetraether indices (TEX86) and magnesium calcium ratios (Mg/Ca) are used to derive palaeotemperature estimates for individual locations using experimentally derived transfer functions [e.g. @Liu2009]. Palaeobiological and lithological climate data provide a different method of reconstructing palaeotemperatures, using e.g. leaf physiognomy and floral assemblages to derive palaeotemperature proxies [@Greenwood2003], or using lithological indicators to determine the range of palaeoclimatic belts [@Scotese2021]. To capture complex dependencies between proxies and climate data, machine learning approaches [@Chandra2021] or articifical neural networks [@Malmgren1997; @Lauchstedt2017] are sometimes used. Earth system models take a fundamentally different approach by modelling the climate-generating processes directly, reconstructing spatially resolved climate estimates for the entire globe [@???]. However, this approach still relies on proxy data to constrain the large number of possible model setups and ground truth the model output [@???] It also requires substantial computing resources and technical expert knowledge, and is thus difficult to implement or modify for most palaeoclimate researchers.

To make inferences on a regional or global scale, proxy-based climate reconstructions need some way of extrapolating a generally sparse record of local findings. Taking the mean of multiple local estimates to summarise regional or global climate variables [e.g. @Veizer2015] is a straightforward approach, but is likely to result in biased climate reconstructions [@Jones2022]. Reconstructions that take into account the spatial distribution of climate data are... ### HERE###
provide an alternative that can be employed more readily by a broad range of workers. Examples of this approach include the visualisation of proxy compilations along a latitudinal gradient [@Hollis2019, @Vickers2021]. Interpolation is sometimes used to bridge spatial gaps in palaeoclimate data [@Taylor2004], taking advantage of the autoregressive nature of climatic data: much of the information on the climate of any given location is contained in the climate data of nearby locations [@Reynolds1994]. Adding to this, some proxy-based reconstructions use statistical modelling to infer climatic patterns. For example, polynomial regression has been used to reconstruct latitudinal temperature gradients [@Bijl2009], and 2D-reconstructions of surface temperatures have been created with Gaussian process regression [@Inglis2020]. 



Here, we present a Bayesian, hierarchical model for inferring sea surface temperatures (SST) that expands upon existing, spatial reconstructions of palaeoclimate by allowing for the integration of 1) prior information based on physical principles and the observed, modern SST distribution, and of 2) geochemical and ecological climate proxies in a common, quantitative framework. We apply this approach to the early Eocene climatic optimum (EECO), the interval with the warmest sustained temperatures of the Cenozoic. Assuming the conservation of thermal tolerances of modern coral reefs and mangrove taxa, we establish broad temperature ranges for EECO coral reef and mangrove sites. We integrate these temperature estimates with the EECO geochemical, shallow marine proxy record to model the latitudinal SST gradient and its uncertainty. 


<!--

Hook -> Generic problem:
- Reconstructing past climate important for understanding current/future global warming
- Two main pathways: highly complex ESM <-> proxy compilations
- Problems with proxy data: only provides a local picture (few local sites interpreted as global signal)
- Problems with ESM (long time to run, very complex, a lot of assumptions on processes/doesn't consider how they may change, need to be constrained with proxy data)
- Lack of intermediate-complexity models to make full use of the proxy data

Specific problem:
- exemplified with the EECO: proxies and ESM hard to reconcile, EECO important climate analogue
- a lot of proxies recrystallised <-> unreliable data or lack of data


Solution:
- Proxy-driven model (no strong assumptions on processes)
- Integrate more data (quantify biological / geological information)
- Integrate additional knowledge (constraints on such gradients)

Application:
- EECO time of extreme warming
- problem of the Early Eocene:
- apply solution to EECO to constrain EECO lat. T gradient

Here:

- EECO specific information
- Disagreement between GCM + geochem data
-->

<!--

The early Eocene climate optimum (EECO, ~ 53--49 million years ago) is thought to have been the warmest episode of [...]. The EECO is of particular interest due to its use as an analogue for extreme warming scenarios, depicting a possible future high-CO2 world. To reconstruct the climate of EECO, a variety of proxy data and Earth System Models have been used. Early modelers have soon noticed that their models struggle to reproduce the climate indicated by proxy data: Without unrealistically high concentrations of atmospheric CO2, early climate models were unable to reproduce the equitable polar climates indicated by early Eocene proxy data, e.g. the occurrence of mangroves in polar latitudes, and d18O data from x indicates a temperature of ~ y at latitude z.  

Contrast between complex, process-driven Earth system models and very simplistic use of the proxy data as local temperature estimates or global averages. Here, we introduce a proxy-driven modelling approach of relatively low complexity, which places the available chemical and biological proxy data in a single climate model.
In order to properly compare model output to proxy data, latitudinal temperature patterns need to be reconstructed from noisy data (impossible to properly compare model gradients with scattered proxy points "by eye")

Reconstructing Earth's climate history is fundamental for understanding the evolution of the Earth system and its consequences for life in the past and future. The geological record, the only empirical source of information on the palaeoclimate of the deep past, holds evidence.  


Here, we present a Bayesian hierarchical model to integrate geological data---with established temperature proxies---into a unified quantitative framework. We apply this approach to the early Eocene climatic optimum (EECO), the interval with the warmest sustained temperatures of the Cenozoic. Assuming the conservation of thermal tolerances of modern coral reefs and mangrove taxa, we establish broad sea surface temperature ranges for EECO coral reef and mangrove sites. We integrate these temperature estimates with the EECO geochemical shallow marine proxy record to model the latitudinal temperature gradient and its uncertainty.

Our hierarchical approach accounts for different sample sizes between and uncertainties within proxy sites, and 

-->

# Materials & Methods

## Geochemical data

Geochemical climate proxy data were extracted from a latest Paleocene and early Eocene compilation [@hollis2019]. This compilation provides four different geochemical proxies for reconstructing seawater temperature: $\delta^18^O, \Delta$_47_, Mg/Ca and TEX_86_. For our analyses, this dataset was restricted to the EECO and samples from the continental shelf. Recrystallised $\delta^18^O samples were also excluded as secondary diagenetic calcite precipitated after deposition can bias isotope measurements and offset temperature values [@schrag1999]. This resulted in most $\delta^18^O samples being excluded from the dataset (x out of x). After data filtering, x geochemical proxy samples remained. For a detailed description of each proxy see [@hollis2019].

## Ecological data

**Coral reefs.** Today, shallow warm-water coral reefs are limited to tropical and subtropical latitudes (~34°N–32 degS), with minimum sea surface temperature (~18 degC) tolerances being the primary constraint on this distribution [@johannes1983; @kleypas1999; @yamano2001]. As coral reefs reside at the upper thermal limit of the oceans today, their maximum sea surface temperature tolerance is less well-constrained with some studies suggesting up to 35.6 degC in the geological past [@jones2022reef]. Nevertheless, the distribution of coral reefs have frequently been recognised as tracers of past (sub-)tropical conditions [@ziegler1984; @kiessling2001]. During the Eocene, coral communities and reefs expanded across tropical and temperate latitudes, with some communities found up to palaeolatitudes of 43 degC N [@zamagni2012]. Using a compilation of Paleocene--early Eocene coral reefs and community localities [@zamagni2012], we generate quantitative sea surface temperature estimates for the ECCO. To do so, we extract localities inferred to be Ilerdian (early Eocene) coral reefs from the compilation, and that can be confidently assigned to the EECO. We exclude coral knobs and coral-bearing mounds which might have broader climatic limits than coral reef ecosystems. This filtering resulted in four unique coral reef localities remaining for the EECO, all of which conform to the modern latitudinal range of coral reefs (<34 deg N). Subsequently, we use statistically derived temperature limits (minimum = 21 degC, average = 27.6 degC, maximum = 29.5 degC) from the published literature [@kleypas1999] to define a normal probability distribution of potential temperature values for coral reef localities. This normal probability distribution was defined with a mean of 27.6 and a standard deviation of 2.125, placing 97.5% of the probability density above the minimum. As the distribution of modern corals is skewed towards warmer temperatures, this approach results in 16.5% of the probability being placed on temperatures > 29.5 degC, allowing for the possibility that Eocene coral reefs were adapted to warmer conditions than modern-day coral reefs.

**Mangroves.** Mangroves are distributed throughout the tropics and subtropics today. While factors beside SST influence the distribution of mangroves, empirical, lower temperature limits have been established for the genera *Avicennia* (15.6 degC) and *Rhizophora* (20.7 degC) [@Quisthoudt2012]. Both *Avicennia* and members of the Rhizophoraceae family were widespread in the early Eocene, but only *Avicennia* occurred at polar latitudes [@Suan2017; @Popescu2021]. Assuming that Eocene members of these mangrove taxa conform to the same climatic requirements as their modern relatives, the presence and absence of *Avicennia* and Rhizophoraceae pollen can be used as a palaeotemperature indicator. For this analysis, published mangrove occurrence data were taken from @Popescu2021, and converted to quantitative temperature estimates. From this data, we identify two types of pollen assemblages which we ascribe different temperature distributions:

1) *Avicennia*-only assemblages ($n=2$): the absence of Rhizophoraceae is indicative of temperatures being between 15.6 degC (lower temperature limt of *Avicennia*) and 20.7 (lower temperature limit of *Rhizophora*). However, a value of 22.5 degC is ascribed as the upper temperature limit here as *Rhizophora* is rare below this temperature. We define the *Avicennia*-only temperature distribution as a normal distribution with a mean of 19.05 degC and a standard deviation of 1.725, resulting in 95% of the probability density being placed within the temperature limits.

2) *Avicennia* and Rhizophoraceae assemblages ($n=5$): the presence of both groups suggests that the locality should have a minimum temperature of 20.7 degC (lower temperature limit of *Rhizophora*). As the upper thermal limits of *Aviciennia* and *Rhizophora* are not well established in @Quisthoudt2012, we assign the same maximum temperature limits (29.5 degC) as coral reef localities as mangroves are also widely distributed throughout tropical regions. Consequently, we define the temperature distribution for this locality as a normal distribution with a mean of 25.1 and a standard deviation of 2.2, with 95% probability density within the temperature limits.



[Fig 1: Map and distribution of proxy data and ecological data]

## Palaeogeographic reconstruction

The palaeogeographic distribution of geochemical and ecological data was reconstructed using the @merdith2021 plate rotation model via the palaeoverse R package ver. XXX (REF). The midpoint age of the EECO (51.2 Ma), along with the present-day coordinates of geochemical and ecological data, were used for palaeorotation.

## Bayesian framework
**Model structure (Fig 2).** We model the mean temperature ($\mu$) at location $j$ as a function of absolute latitude ($abs(l)$) with a logistic regression (`growth curve` or `Richard's curve`) of the form:

$$\mu_{j}  \sim N(\nu_j, \sigma), $$

$$\nu_{j} = A~+\frac{K-A}{e^{B(abs(l_j)-M)}}~, ~~~~~ j = 1,...,n,  $$
where $A$ and $K$ denote the lower and upper asymptote, respectively, $M$ specifies the latitude of maximal growth, the most quickly with latitude, $B$ denotes the growth rate (Fig. 2), $\sigma$ denotes the residual standard deviation, and $n$ denotes the number of locations.

We infer $\mu_j$ from $m$ individual temperature observations $t_{i = 1,...m}$, derived from geochemical data, at location $j$ as

$$t_{i,j}  \sim N(\mu_j, \sigma_j), ~~~~~ i = 1,...,m,  $$
where $m$ is the number of observations at each location, and $\sigma_j$ is the estimated standard deviation of the temperatures at location $j$.

Similarly, $\mu_j$ is inferred for locations with ecological proxies from the associated normal temperature distributions with a given mean and standard deviation, $t_{\mu,j}$ and $t_{\sigma,j}$, as

$$t_{\mu,j}  \sim N(\mu_j,t_{\sigma,j}).  $$

This structure implies that $\mu_j$ is not fixed at the mean proxy temperature at location $j$, <!--of the temperatures $t_{i=1,...,m,~j}$ of location $j$-->, but is drawn towards the overall logistic regression curve, i.e. towards $\nu_j$. The pull towards $\nu_j$ tends to be high when $m$ is low, when the observations $t_{i=1,...,m,~j}$ are scattered, i.e. $\sigma_j$ is high, and/or when the overall standard deviation $\sigma$ is low. In practice, this has the desirable consequence that locations with few observations and large temperature differences between observations have less influence on the overall regression than well-sampled locations with consistent temperature observations.

**Priors (Fig2x).** In the Bayesian framework, priors need to be placed on the unknown parameters of a model. We placed weakly informative, conjugate inverse-gamma priors on $\sigma$ and $\sigma_{j=1,..n}$:
$$\sigma  \sim \sqrt{Inv-Gamma(\alpha+\frac{n}{2},\beta + 0.5\times(\mu_j-\nu_j))}, ~~~~~ j = 1,...,n,  $$
$$\sigma_j  \sim \sqrt{Inv-Gamma(\alpha+\frac{m}{2},\beta + 0.5\times(t_{i,j}-\mu_j))}, ~~~~~ i = 1,...,m,~~~~~j = 1,...,n. $$
We set $\alpha = \beta = 1$, allowing these priors to be quickly overwhelmed by the data as $n$ and $m$ increase, as we have little *a priori* knowledge of these parameters.

In contrast, we put informative priors on the regression coefficients $A$, $K$, $M$ and $B$, based on physical principles, and vaguely based on the modern climate system:  

**A.** Predicted seawater surface temperatures are not allowed to be $<< -2^\circ C$, the freezing point of sea water. The highest prior density of $A$ is placed around $0^\circ C$, and it slowly tapers off towards higher temperatures. This shape is achieved by placing a skew-normal prior on the lower asymptote, specified as
$$A \sim SN(\xi=-3.0,\omega=12,\alpha_{SN}=30),$$
where $\xi$, $\omega$, and $\alpha_{SN}$ are the location, scale and shape parameters.  

**K.** Input of solar energy decreases from the tropics to the poles. Hence, the latitudinal temperature gradient is broadly negative, i.e. temperature decreases with absolute latitude. This is achieved by setting $K \ge A$. The prior on the upper asymptote $K$ is a truncated normal distribution with the mean set to $K$ of the modern SST gradient, with a broad standard deviation:
$$K \sim TN(\mu_{TN} = 28, \sigma_{TN} = 10, \alpha_{TN} = A, \beta_{TN}= \infty)$$
The distribution is truncated to the left at $\alpha_{TN}=A$, but not truncated to the right ($\beta_{TN}$).  

**M.** The steepness of the gradient is presumed to be highest in mid-latitudes; this is expressed with a normal prior on $M$ with the mean set to $M$ of the modern SST gradient:
$$M \sim N(42,10)$$
**B.** The steepness or growth rate $B$ of the gradient is constrained to be $\ge0$ and to not be exceedingly high, as oceanic and atmospheric heat transfer is bound to prevent very abrupt SST changes across latitudes. A gamma-distributed prior of the form
$$B \sim Gamma(\alpha_G=4.3,\beta_G=30)$$
was placed on $B$. The shape and rate parameters $\alpha_G$ and $\beta_G$ were chosen such that the highest prior density is at $B$ of the modern SST gradient, $0.11$.

[Fig. 2: Model structure and visualisation of parameters and priors]


## Model validation
To test whether our logistic regression model can adequately describe latitudinal temperature gradients, we applied a simplified version of the model to modern sea surface temperatures from Bio-Oracle [@...]. As these modern, annual sea surface temperatures estimates are associated with little uncertainty, there is no need for a hierarchical model structure, and we substituted temperature ($t$) for $\mu$ in eq. ? and ?. To verify that the modern gradient can be approximated with limited sampling, we resampled modern sea surface temperatures at modern latitudes corresponding the palaeolatitudes of the Eocene samples. This process was repeated 100 times, randomly chosing a longitude for each latitude in each repetition. The parameters of the non-hierarchical temperature model were estimated for each of the 100 samples, and the iterations after burn-in from the posterior of the parameters were pooled to generate the resulting median temperature gradient with 95 % credible intervals ($2.5^{th}$ to $97.5^{th}$ percentile).


## Parameter estimation
We estimated the posterior distributions of the model parameters using a Markov chain Monte Carlo (MCMC) algorithm, written in R. Specifically, we sampled the unknown parameters $A$, $K$, $M$ and $B$ with Metropolis-Hastings, and used Gibbs sampling to estimate all other unknown parameters. Posterior inference on the modern gradient is based on four chains with 60,000 iterations each, 10,000 of which were discarded as burn-in, and keeping every 10th iteration, resulting in a total of 20,000 iterations. The modern temperature gradient with the Eocene sampling distribution was estimated in one chain with 25,000 iterations for each of the 100 temperature samples. 5,000 iterations each were discarded as burn-in, and every 10th iteration was kept, resulting in a total of 200,000 iterations across all 100 model runs.
For the Eocene model, we ran four chains with 600,000 iterations each, discarding 100,000 as burn-in and keeping every 100th iteration, as the hierarchical model structure results in higher autocorrelation of the chains. The Eocene posterior inference is thus based on a total of 20,000 iterations with low autocorrelation (effective multivariate sample size for $A$, $K$, $M$ and $B$ is > 18,000). Trace plots were used to assess the convergence and mixing of the MCMC chains (Supplementary Materials S1).


## Processing of model results
<!--
- Calculate lat gradient
- Calculate global T
[Fig. 4]
-->
Modelled sea surface temperature estimates were generated with eq. ?, calculating the sea surface temperatures at any latitude with the parameter estimates of each iteration from the posterior. The median, $2.5^{th}$ and $97.5^{th}$ percentile of temperatures where then taken from all temperature estimates obtained at the latitude of interest.

Differences between Eocene and modern temperatures at a certain latitude were calculated by randomly pairing all iterations of the posterior from the Eocene and modern temperature gradient model, calculating the Eocene and modern temperature using the respective iterations, taking the difference, and then calculating the median ($2.5^{th}$, $97.5^{th}$ percentile) from all pairs of iterations.  

Global average temperatures were calculated by taking the weighted mean of the median ($2.5^{th}$, $97.5^{th}$ percentile) temperature estimates in 1 degree latitudinal bins. The weights were set to the proportion of global surface area in each latitudinal bin, i.e. decreasing with increasing latitude as:
$$weights = sin(\alpha_{1,i}) - sin(\alpha_{2,i}) ,$$
where $\alpha1$ is the upper, and $\alpha2$ is the lower latitudinal boundary of bin $i$.


# Results
```{r results block - for in-line code, echo = FALSE}
setwd('..') # move up to parent folder of /manuscript

# temperature gradients
tdiff_lat0 <- readRDS("results/eeco/eocene_modern_difference_equator.rds")
tdiff_lat90 <- readRDS("results/eeco/eocene_modern_difference_poles.rds")
eocene_gradient <- readRDS("results/eeco/eocene_overall_gradient.rds")
modern_gradient <- readRDS("results/modern/modern_overall_gradient.rds")
modern_eocene_gradient <- readRDS("results/modern/modern_eocene_sampling_overall_gradient.rds")
modern_eocene_gradient_diff <- readRDS("results/modern/modern_eocene_sampling_overall_gradient_diff.rds")
                           
# sdy
eeco_sdy <- readRDS("results/eeco/eeco_sdy.rds")
modern_eeco_sample_sdy <- readRDS("results/modern/modern_eeco_sample_sdy.rds")
modern_sdy <- readRDS("results/modern/modern_sdy.rds")


# global average temperatures
motemp_global <- readRDS("results/modern/global_mean_modern.rds")
eotemp_global <- readRDS("results/eeco/global_mean_eeco.rds")
moeotemp_global <- readRDS("results/eeco/global_mean_modern_eocene_sampling_eeco.rds")
moeotemp_global_diff <- readRDS("results/eeco/global_mean_modern_eocene_sampling_difference.rds")


```
## Model validation
<!-- - Show that the 4-parameter logistic function can adequatly describe the modern temperature gradient
- Show that the modern gradient can be reproduced with Eocene sampling distribution
-->
[Fig 3 - Modern gradient]
The average modern temperature gradient can be closely approximated with our model when using the full modern SST dataset (Fig. 3a). Reducing the amount and the spatial coverage of data points to match the early Eocene sampling distribution ($n = 34$) still results in a close match of the modeled gradient with the empirical gradient (Fig. 3b). The 95% credible interval of reconstructed gradients (Fig. 3b) is noticeably narrower than the spread of empirical temperature values (Fig. 3a). The modern, latitudinal gradient, modeled with all data, is `r modern_gradient$"50%"` degC, and has a median of `r modern_eocene_gradient$"50%"`  (95% CI: `r modern_eocene_gradient$"2.5%"` - `r modern_eocene_gradient$"97.5%"`) degC when modelled with only the early Eocene sampling locations. A random sampling of modern temperatures at latitudes corresponding to the sampled Eocene palaeolatitudes would thus allow the reconstruction of the modern latitudinal temperature gradient with good accuracy, with expected deviations from the actual gradient as low as `r modern_eocene_gradient_diff$"2.5%"` to `r modern_eocene_gradient_diff$"97.5%"` degC (95 % CI).

The modeled, latitudinal temperature gradient facilitates accurate reconstruction of global average temperatures. The modern, global mean sea surface temperature estimate is `r motemp_global$"50%"` degC when using the full, modern data set. When reduced to the early Eocene sampling distribution, the modern global mean sea surface temperature is estimated at `r moeotemp_global$"50%"` (95% CI: `r moeotemp_global$"2.5%"` - `r moeotemp_global$"97.5%"`) degC. The deviations from the full modern estimate are again very low, with a 95 % credible interval of `r moeotemp_global_diff$"2.5%"` to `r moeotemp_global_diff$"97.5%"` degC.


## EECO reconstruction

The modeled Eocene temperature gradient is starkly different from the modern (Fig 4). Modelled, median equatorial temperatures are `r tdiff_lat0$"50%"` (95% CI: `r tdiff_lat0$"2.5%"` - `r tdiff_lat0$"97.5%"`) degC higher for the Eocene, and polar temperatures are higher by `r tdiff_lat90$"50%"` (95% CI: `r tdiff_lat90$"2.5%"` - `r tdiff_lat90$"97.5%"`) degC. This results in a strongly flattened latitudinal temperature gradient of `r eocene_gradient$"50%"`  (95% CI: `r eocene_gradient$"2.5%"` - `r eocene_gradient$"97.5%"`) degC for the Eocene, as opposed to `r modern_gradient$"50%"` degC for the modern. 

The high variability of early Eocene palaeotemperature proxies, particularly in the mid-latitudes, and the scarcity of high-latitude data, result in substantial uncertainties in the modeled temperature gradient. This is reflected in the residual standard deviation ($\sigma$) of the early Eocene gradient, `r eeco_sdy$"50%"` (95% CI: `r eeco_sdy$"2.5%"` - `r eeco_sdy$"97.5%"`) degC, more than twice as high than  $\sigma$ of the modern gradient, `r modern_sdy$"50%"`. 

The global Eocene mean sea surface temperature is estimated at `r eotemp_global$"50%"` (95% CI: `r eotemp_global$"2.5%"` - `r eotemp_global$"97.5%"`) degC, significantly higher than the modern (`r motemp_global$"50%"` degC). 

For comparison, a model run excluding the ecological proxies results in a global mean temperature of  
The inclusion of ecological proxy data only slightly reduces the overall model standard deviation (Supplementary materials). 


## Fig 4 - compare Eocene gradient with modern gradient, also with previous reconstructions / ES models?

- x1 Draw samples from the posterior gradient to get a latitudinal gradient of deg C / deg lat with uncertainty (intercept gradient at 0 and 90 deg lat)

- x2 generate global average temperature, and tropical, temperate, polar temperatures in a similar way, accounting for area

# Discussion

**Eocene temperature gradients.**


**Methodological advances.** Latitudinal temperature gradients have been estimated with a variety of parametric and non-parametric statistical techniques. Parametric methods include polynomials [@Greenwood1995; @Bijl2009] and a cosine function [@Inglis2020]. Whilst some of those functions are flexible enough to model a range of empirical temperature gradients, the logistic function used herein has the added advantage of an easily understandable relationship between each of the model parameters and the shape of the latitudinal gradient (Fig. 2). Non-parametric models can very flexibly follow the shape of an unknown temperature gradient [@Jones2022, but see @Zhang2019], but have the disadvantage of having no model parameters that can be compared between data sets. Parametric methods should therefore be preferred to non-parametric temperature gradient models, as long as very broad prior information on the shape of the gradients exists. The ease with which such prior information can be integrated is perhaps the major advantage of our method: The Bayesian framework allows to specify arbitrary priors on the four parameters that control the upper and lower temperature limits, the steepness of the gradient, and the latitudinal position of the steepest point in the gradient (see Methods). A further improvement to existing methods is that the hierarchical structure of our model explicitly accounts for variation of temperature estimates at individual localities, and for uncertainty associated with the ecological temperature proxies. An extension of the model additionally accounts for measurement uncertainty of the geochemical proxies (Supplementary Materials).

**Comparison to Eocene proxy and modelling studies**. 

A major theme of the discussions on the early Eocene greenhouse climate has been the discrepancy between proxy records, particularly ecological climate indicators such as macrofloral assemblage data, have 

- x1 compare lat gradient to literature estimates, e.g. Zhang2019
- compare lat gradient to climate models and the "early EECO problem"
- discuss insufficiency of proxies (high variability, ...)
- discuss utility of the model and future applications

# Conclusions

# Acknowledgements

# Author contributions

# Data accessibility

# References
