---
title: "Supplementary material for  \nBayesian multi-proxy reconstruction of the early Eocene latitudinal temperature gradient"
author:
  - Kilian Eichenseer^[Department of Earth Sciences, Durham University, South Road, DH1 3LE, Durham, United Kingdom] and Lewis A. Jones^[Centro de Investigación Mariña, Grupo de Ecoloxía Animal, Universidade de Vigo, 36310 Vigo, Spain]
output:
  word_document:
    reference_docx: "template.docx"


bibliography: references.bib
csl: palaeontology.csl



---
## Hierarchical, Bayesian model for latitudinal temperature gradients

**Model structure (Fig 2).** We model the mean temperature ($\mu$) at location $j$ as a function of absolute latitude ($abs(l)$) with a logistic regression (`growth curve` or `Richard's curve`) of the form:

$$\mu_{j}  \sim N(\nu_j, \sigma), $$

$$\nu_{j} = A~+\frac{K-A}{e^{B(abs(l_j)-M)}}~, ~~~~~ j = 1,...,n,  $$
where $A$ and $K$ denote the lower and upper asymptote, respectively, $M$ specifies the latitude of maximal growth, the most quickly with latitude, $B$ denotes the growth rate (Fig. 2), $\sigma$ denotes the residual standard deviation, and $n$ denotes the number of locations.

We infer $\mu_j$ from $m$ individual temperature observations $t_{i = 1,...m}$, derived from geochemical data, at location $j$ as

$$t_{i,j}  \sim N(\mu_j, \sigma_j), ~~~~~ i = 1,...,m,  $$
where $m$ is the number of observations at each location, and $\sigma_j$ is the estimated standard deviation of the temperatures at location $j$.

Similarly, $\mu_j$ is inferred for locations with ecological proxies from the associated normal temperature distributions with a given mean and standard deviation, $t_{\mu,j}$ and $t_{\sigma,j}$, as

$$t_{\mu,j}  \sim N(\mu_j,t_{\sigma,j}).  $$

This structure implies that $\mu_j$ is not fixed at the mean proxy temperature at location $j$, <!--of the temperatures $t_{i=1,...,m,~j}$ of location $j$-->, but is drawn towards the overall logistic regression curve, i.e. towards $\nu_j$. The pull towards $\nu_j$ tends to be high when $m$ is low, when the observations $t_{i=1,...,m,~j}$ are scattered, i.e. $\sigma_j$ is high, and/or when the overall standard deviation $\sigma$ is low. In practice, this has the desirable consequence that locations with few observations and large temperature differences between observations have less influence on the overall regression than well-sampled locations with consistent temperature observations.

**Priors (Fig2x).** In the Bayesian framework, priors need to be placed on the unknown parameters of a model. We placed weakly informative, conjugate inverse-gamma priors on $\sigma$ and $\sigma_{j=1,..n}$:
$$\sigma  \sim \sqrt{Inv-Gamma(\alpha+\frac{n}{2},\beta + 0.5\times(\mu_j-\nu_j))}, ~~~~~ j = 1,...,n,  $$
$$\sigma_j  \sim \sqrt{Inv-Gamma(\alpha+\frac{m}{2},\beta + 0.5\times(t_{i,j}-\mu_j))}, ~~~~~ i = 1,...,m,~~~~~j = 1,...,n. $$
We set $\alpha = \beta = 1$, allowing these priors to be quickly overwhelmed by the data as $n$ and $m$ increase, as we have little *a priori* knowledge of these parameters.

In contrast, we put informative priors on the regression coefficients $A$, $K$, $M$ and $B$, based on physical principles, and vaguely based on the modern climate system:  

**A.** Predicted seawater surface temperatures are not allowed to be $<< -2^\circ C$, the freezing point of sea water. The highest prior density of $A$ is placed around $0^\circ C$, and it slowly tapers off towards higher temperatures. This shape is achieved by placing a skew-normal prior on the lower asymptote, specified as
$$A \sim SN(\xi=-3.0,\omega=12,\alpha_{SN}=30),$$
where $\xi$, $\omega$, and $\alpha_{SN}$ are the location, scale and shape parameters.  

**K.** Input of solar energy decreases from the tropics to the poles. Hence, the latitudinal temperature gradient is broadly negative, i.e. temperature decreases with absolute latitude. This is achieved by setting $K \ge A$. The prior on the upper asymptote $K$ is a truncated normal distribution with the mean set to $K$ of the modern SST gradient, with a broad standard deviation:
$$K \sim TN(\mu_{TN} = 28, \sigma_{TN} = 10, \alpha_{TN} = A, \beta_{TN}= \infty)$$
The distribution is truncated to the left at $\alpha_{TN}=A$, but not truncated to the right ($\beta_{TN}$).  

**M.** The steepness of the gradient is presumed to be highest in mid-latitudes; this is expressed with a normal prior on $M$ with the mean set to $M$ of the modern SST gradient:
$$M \sim N(42,10)$$
**B.** The steepness or growth rate $B$ of the gradient is constrained to be $\ge0$ and to not be exceedingly high, as oceanic and atmospheric heat transfer is bound to prevent very abrupt SST changes across latitudes. A gamma-distributed prior of the form
$$B \sim Gamma(\alpha_G=4.3,\beta_G=30)$$
was placed on $B$. The shape and rate parameters $\alpha_G$ and $\beta_G$ were chosen such that the highest prior density is at $B$ of the modern SST gradient, $0.11$.

## Convergence checks
To ensure the convergence and mixing of the chains, we inspected traceplots of all the unknown parameters of the model. [Add figures]

# References
